#!/bin/bash

case $1 in
    # to be compatible with mu server
    server)
	exec socat -t 0 UNIX-CONNECT:$HOME/.mc_server_sock -
	;;
    *)
	# this is force quoting all arguments
	Command="(mc \"$1\""
	shift
	for Arg in "$@"; do
	    Command+=" \"$Arg\""
	done
	echo "$Command)" | socat -t 10 UNIX-CONNECT:$HOME/.mc_server_sock -
	;;
esac
